create table attachment_order_table (compute_id varchar(255), device varchar(255), volume_id varchar(255), id varchar(255) not null, primary key (id))
create table attribute_value_range (id bigint not null, saml_attributes varchar(255), range_id varchar(255) not null, primary key (id, range_id))
create table compute_order_table (allocation_instances integer, allocation_ram integer, allocation_vcpu integer, disk integer, image_id varchar(255), memory integer, name varchar(255), public_key varchar(1024), extra_user_data_file_content varchar(4096), extra_user_data_file_type integer, vcpu integer, id varchar(255) not null, primary key (id))
create table compute_order_networks_id (compute_order_id varchar(255) not null, networks_id varchar(255))
create table federation_user_token (id bigint generated by default as identity, token_provider varchar(255), user_id varchar(255), user_name varchar(255), primary key (id))
create table ldap_token (id bigint not null, primary key (id))
create table network_order_table (allocation_mode varchar(255), cidr varchar(255), gateway varchar(255), name varchar(255), id varchar(255) not null, primary key (id))
create table open_stackv3token (project_id varchar(255), id bigint not null, primary key (id))
create table order_table (id varchar(255) not null, cached_instance_state integer, instance_id varchar(255), order_state varchar(255), providing_member varchar(255), requesting_member varchar(255), federation_user_token_id bigint, primary key (id))
create table public_ip_order_table (compute_order_id varchar(255), id varchar(255) not null, primary key (id))
create table shibboleth_token (id bigint not null, primary key (id))
create table signed_federation_user_token (signature varchar(1024), id bigint not null, primary key (id))
create table timestamped_signed_federation_user_token (timestamp bigint, id bigint not null, primary key (id))
create table volume_order_table (name varchar(255), volume_size integer, id varchar(255) not null, primary key (id))
alter table attachment_order_table add constraint FK9g6g9eciiahnt2n9h51b4uj foreign key (id) references order_table
alter table attribute_value_range add constraint FKfkoidlipb8jw50i8daqkiq5t3 foreign key (id) references shibboleth_token
alter table compute_order_table add constraint FKnva8y79x2pr0olr9l2x0708i3 foreign key (id) references order_table
alter table compute_order_networks_id add constraint FKqgscnboubwiywhml8oufd8qny foreign key (compute_order_id) references compute_order_table
alter table ldap_token add constraint FK5a7y10ueogu9ycvcy0es4yc83 foreign key (id) references timestamped_signed_federation_user_token
alter table network_order_table add constraint FKp9vqkr5j23532e3gsmd86cevh foreign key (id) references order_table
alter table open_stackv3token add constraint FK5mcrbdb6wqa2nndcec821j5j9 foreign key (id) references signed_federation_user_token
alter table order_table add constraint FK3bhgvemwk2ol0caifo5nsd9ef foreign key (federation_user_token_id) references federation_user_token
alter table public_ip_order_table add constraint FK5de922p7iou293ogkg553tx6j foreign key (id) references order_table
alter table shibboleth_token add constraint FKawow0wxqbt1jvrq6ve7da2trv foreign key (id) references timestamped_signed_federation_user_token
alter table signed_federation_user_token add constraint FKp3yc1yw9pdb96c6qj80sfej1g foreign key (id) references federation_user_token
alter table timestamped_signed_federation_user_token add constraint FK54se1csjigc5utsw1lnehuf93 foreign key (id) references signed_federation_user_token
alter table volume_order_table add constraint FKmjgrmkoe4fiei7vrx3o8xhtcc foreign key (id) references order_table

