#!/bin/bash

echo "Run this script in the project folder."
echo "(e.g.) sudo bash ./docker/build latest"
read -n 1 -s -r -p "Press any key to continue"

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <docker tag>"
    exit 1
fi

tag=$1

mvn package
sudo docker build --no-cache -t wesleymonte/probes:$tag -f docker/Dockerfile .